export const SET_AUTHENTICATED='SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED='SET_UNAUTHENTICATED';
export const SET_USER='SET_USER';
export const LOADING_USER='LOADING_USER';

//transaction Form
export const SET_TRANSACTION='SET_TRANSACTION';
export const COMPLETE_TRANSACTION='COMPLETE_TRANSACTION';
export const SET_Qoute='SET_Qoute';
export const ONGOING_TRANSACTION='ONGOING_TRANSACTION';


export const SET_ERRORS='SET_ERRORS';
export const LOADING_UI='LOADING_UI';
export const CLEAR_ERROR='SET_AUTHENTICATED';






